name: VehicleRental CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore VehicleRental/VehicleRental.sln

      - name: Build
        run: dotnet build VehicleRental/VehicleRental.sln --no-restore

      - name: Run Unit Tests
        run: dotnet test VehicleRental/Tests/VehicleRental.Tests.Unit/VehicleRental.Tests.Unit.csproj --no-build --verbosity normal

      - name: Run Integration Tests
        run: dotnet test VehicleRental/Tests/VehicleRental.Tests.Integration/VehicleRental.Tests.Integration.csproj --no-build --verbosity normal
