name: VehicleRental CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Add permissions for the test reporter
permissions:
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore VehicleRental/VehicleRental.sln

      - name: Build
        run: dotnet build VehicleRental/VehicleRental.sln --no-restore

      - name: Run Unit Tests
        run: dotnet test VehicleRental/Tests/VehicleRental.Tests.Unit/VehicleRental.Tests.Unit.csproj --no-build --verbosity normal --logger "trx;LogFileName=unit-test-results.trx"

      - name: Report Unit Test Results
        uses: dorny/test-reporter@v1
        if: always() # Run this step even if tests fail
        with:
          name: Unit Tests Results
          path: VehicleRental/Tests/VehicleRental.Tests.Unit/unit-test-results.trx
          reporter: dotnet-trx
          fail-on-error: "true"

      - name: Run Integration Tests
        run: dotnet test VehicleRental/Tests/VehicleRental.Tests.Integration/VehicleRental.Tests.Integration.csproj --no-build --verbosity normal --logger "trx;LogFileName=integration-test-results.trx"

      - name: Report Integration Test Results
        uses: dorny/test-reporter@v1
        if: always() # Run this step even if tests fail
        with:
          name: Integration Tests Results
          path: VehicleRental/Tests/VehicleRental.Tests.Integration/integration-test-results.trx
          reporter: dotnet-trx
          fail-on-error: "true"
